const tintColorLight = '#123D5C'; 
const tintColorDark = '#E4C9A2'; 

export default {
  light: {
    text: '#2C190A', 
    textLight: '#7A6957',
    background: '#123D5C', 
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    cardBackground: '#F3E1C4', 
    borderColor: '#D2BFA5',
    headerBackground: '#E4C9A2', 
    headerText: '#2C190A',
    sectionTitle: '#123D5C',
    inputBackground: '#E5D0B1', 
    placeholderText: '#7A6957',
    buttonPrimary: '#8BA75A', 
    buttonText: '#FFFFFF',
    danger: '#C0392B',
  },
  dark: {
    text: '#E0E0E0', 
    textLight: '#A0A0A0',
    background: '#121212', 
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    cardBackground: '#1E1E1E', 
    borderColor: '#333333',
    headerBackground: '#1E1E1E', 
    headerText: '#E4C9A2', 
    sectionTitle: '#E4C9A2', 
    inputBackground: '#2C2C2C',
    placeholderText: '#666666',
    buttonPrimary: '#8BA75A', 
    buttonText: '#FFFFFF',
    danger: '#CF6679', 
  },
};
